name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install codecov
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        pip install pytest pytest-cov
        pytest --ignore "sample_test_script/" --cov=./
        codecov --token=$CODECOV_TOKEN
    - name: Get current package version
      id: get_version
      run: echo "::set-output name=version::$(python setup.py --version)"

    - name: Compare package versions
      id: compare_versions
      run: |
        pip install counterplots
        if [[ "$(python -m pip show counterplots | grep Version | awk '{print $2}')" == "${{ steps.get_version.outputs.version }}" ]]; then
          echo "Versions match. No upload needed."
          echo "::set-output name=upload_required::false"
        else
          echo "Versions differ. Uploading package..."
          echo "::set-output name=upload_required::true"
        fi
        pip uninstall counterplots -y
    - name: Upload to PyPI
      if: steps.compare_versions.outputs.upload_required == 'true'
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install twine
        python setup.py sdist
        twine upload dist/*
